### ISSUE TITLE
Why dont you delete wikidata-cli npm?

### ISSUE THREAD

**Issue by yuiseki** [maxlath/wikibase-cli#147]
Thank you for your very useful project, wikibase-cli.
We ran into the problem of installing the old wikidata-cli by mistake and confused.
So How about removing the old wikidata-cli npm?

https://www.npmjs.com/package/wikidata-cli

**Comment by maxlath** [comment]
I would be against removing it from npm as, if it was possible (which I'm not certain of), it would open the possibility for squatting: a new possibly malicious project reusing the name and being installed by users trusting this package. Instead, I turned wikidata-cli into an [empty shell with a message to install wikibase-cli instead](https://github.com/maxlath/wikibase-cli/blob/a95a4d6b/bin/wd) and published it as a new major version, so that new projects running `npm install wikidata-cli` get it, but not old projects using an earlier version: should be enough to avoid the confusion right?
