### ISSUE TITLE
wb query numeric object value for property

### ISSUE THREAD

**Issue by HakanIST** [maxlath/wikibase-cli#85]
Hello,

The query:  

`wb query --property P2448 --object 2217527 `

returns no results however  the query `wb claims Q138172 P2448` shows corresponding result. 
Thanks in advance,

**Comment by maxlath** [comment]
it works when you make the object explicitly a string
```sh
wd query --property P2448 --object '"2217527"'
```
In this case the tool could check the property datatype to format it correctly, but sometimes the property isn't provided.

Another solution  would be to always query both the string and the number formats, but then you can't make the query that wants one and not the other, so that's not totally satisfying I guess

**Comment by HakanIST** [comment]
First solution works very well. Thank you.
