### ISSUE TITLE
meta-wiki autoconfirmed userAccount necessary to request OAuth token 

### ISSUE THREAD

**Issue by jum-s** [maxlath/wikibase-cli#96]
A wikimedia user need to be autoconfirmed on [meta-wiki](https://meta.wikimedia.org/wiki/Special:UserRights/Jumtist) to be able to request Oauth token.
A user to make a few edits before being able to be autoconfirmed, it might be problematic for users who do not use meta-wiki so much.
Since wikidata do not provide a consumer registration feature (`Special:OAuthConsumerRegistration`), maybe it would make more easier to create a Oauth consumer directly on wikidata, to create credentials

**Comment by maxlath** [comment]
unfortunately, it seems it can't be created on Wikidata itself, [`Special:OAuthConsumerRegistration/propose`](https://www.wikidata.org/wiki/Special:OAuthConsumerRegistration/propose) doesn't exist :/

**Comment by maxlath** [comment]
good news! there is an option to not give your password, and give limited rights to wikibase-cli by setting up a [bot password](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#using-your-username-and-a-bot-password): so that's what wikibase-cli prompt now recommends (58ca02c)

I also added a [warning on the rights issue in `wikibase-edit` documentation](https://github.com/maxlath/wikibase-edit/blob/master/docs/how_to.md#owner-only-oauth-consumer)
